### ISSUE TITLE
Internet Archive check failes with undefined method `content' for nil:NilClass

### ISSUE THREAD

**Issue by henryborchers** [medusa-project/book-tracker#45] opened 2023-12-20 18:09 UTC
When running Internet Archive check in BookTracker, I get a message that the task failed. 

The message I can see is...
Internet Archive check failed: undefined method `content' for nil:NilClass

**Comment by adolski** [comment] 2023-12-20 22:06
@gaurijo Could you look into this?

**Comment by gaurijo** [comment] 2023-12-20 22:21
@adolski The live Book Tracker site is not up to date with whatever has been merged to our `develop` branch. Our `production branch` is not up to date with the `demo branch`, and demo branch is also not up to date with the develop branch. 

**I couldn't reproduce the error locally, so I think it's failing due to the above.**

`Local server/development:`

![Image](https://github.com/medusa-project/book-tracker/assets/103534307/36aa5904-d2a5-421e-aaf7-a507761f2c9f)

`Production:`

![Image](https://github.com/medusa-project/book-tracker/assets/103534307/a58fae82-7b9d-4774-a03d-c56f18ea16a6)

~~Was this service check triggered automatically after running an import? With the changes we've made, there shouldn't be a way to run the Hathi or Internet Archive service checks manually, right?~~

**Comment by gaurijo** [comment] 2024-01-11 18:42
@adolski Going back to this issue, I think the error will be resolved by

1. merging develop into demo
2. merging demo into production
3. and then deploying to production

If that sounds okay to you, I can go ahead with that.

**Comment by adolski** [comment] 2024-01-11 18:47
Absolutely, go right ahead.

**Comment by henryborchers** [comment] 2024-01-11 20:46
When I ran it this month, I didn't run into the same problem.

**Comment by gaurijo** [comment] 2024-01-11 21:12
@adolski Unfortunately I'm running into the same disk space error when I try to deploy. Last time this happened I had increased the ephemeral storage and that fixed it, so I'm not sure why it's happening again. 



![Image](https://github.com/medusa-project/book-tracker/assets/103534307/8ef19dcb-bd99-4390-948e-b2084a02e2c0)

**Comment by adolski** [comment] 2024-01-11 21:21
By chance, do you have a large `log/development.log` file?

**Comment by gaurijo** [comment] 2024-01-11 21:23
Yes, almost 60 GB!

![Image](https://github.com/medusa-project/book-tracker/assets/103534307/23d39b80-289c-4c03-a33f-a051e7667170)

**Comment by adolski** [comment] 2024-01-11 21:38
Bingo! That also explains the need for more ephemeral storage for the Fargate task and why your images are so big.

I've just pushed a commit to add `/log` to the `.dockerignore` file so that it won't include log files in the image anymore. That ought to fix this.

And I've updated `config/environments/development.rb` to modify the logger to log only to stdout, so it won't create a log file anymore.

**Comment by gaurijo** [comment] 2024-01-11 21:50
Excellent! I pulled your latest commits and merged everything into demo/prod. 

Just ran another deploy to prod and we're in the green. I'll go ahead and close this issue since it sounds like @henryborchers is no longer running into errors.

**Closed as completed by gaurijo** 2024-01-11 21:50 UTC
